language: generic

notifications:
  email:
    - maxim@synrc.com
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: change  # options: [always|never|change] default: always
    on_start:   always  # options: [always|never|change] default: always

cache:
  directories:
  - $HOME/.stack

addons:
  apt:
    packages:
      - bnfc
      - libgmp-dev

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - git clone git://github.com/mortberg/cubicaltt
  - cd cubicaltt
  - git checkout hcomptrans
  - stack init
  - printf "\nextra-deps:\n" >> stack.yaml
  - printf "  - BNFC-2.8.1\n" >> stack.yaml
  - cabal install alex happy bnfc
  - cabal install
  - ls
  - stack build
  - ls ./.stack-work/dist/x86_64-linux
  - cd ..
  - ./cubicaltt/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/cubical/cubical -b src/hopf.ctt
